logging.level:
  com.example: debug
  io.r2dbc.h2: error
spring:
  #  profiles.active: restrict-users
  security.oauth2.client.registration:
    google:
      client-id: <todo>
      client-secret: <todo>
    facebook:
      client-id: <todo>
      client-secret: <todo>
    github:
      client-id: <todo>
      client-secret: <todo>
