logging:
  level:
    com.example: debug
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <todo>
            client-secret: <todo>
          facebook:
            client-id: <todo>
            client-secret: <todo>
          github:
            client-id: <todo>
            client-secret: <todo>
